# Site settings
title: Les petites baies noires
long_title: Les petites baies noires
email: sebastien@boyron.eu
description: > # this means to ignore newlines until "baseurl:"
        Les petites baies noires, un domaine situé au coeur des corbières.
        C'est au coeur du terroir de blablabla que ce vin est cultivé et confectionné.
baseurl: "lespetitesbaiesnoires" # the subpath of your site, e.g. /blog/
url: "http:///www.sebastien.boyron.eu" # the base hostname & protocol for your site

twitter_username: 
github_username:


# Build settings
markdown: kramdown

paginate: 5
paginate_path: "posts/page:num/"

